### ISSUE TITLE
Can not get the file of Drop Data CSV 

### ISSUE THREAD

**Issue by shenyigang** [CIDARLAB/uDrop-Generation#2]
Thanks for your time.
I think it is a useful program for analyzing the droplet in the microfluidic channel. However, when I ran the code, it shows some problem,  I could not get the output file of Drop Data CSV (Just sin data), does the analyzing movie file have a limitation, I took a video ( 30s ) for running the code. If you can help me solve this problem, that will be great.

feedback:
Traceback (most recent call last):
  File "C:\Users\dmush\Anaconda3\lib\tkinter\__init__.py", line 1705, in __call__
    return self.func(*args)
  File "D:\uDROP_Generation.py", line 230, in confirm
    analysis = Analysis(fps, conversion_factor, start_x, start_y, width,height, self.frame_list, self.vid_path)
  File "D:\uDROP_Generation.py", line 336, in __init__
    self.runAnalysis()
  File "D:\uDROP_Generation.py", line 360, in runAnalysis
    self.getAllDiameters()
  File "D:\uDROP_Generation.py", line 529, in getAllDiameters
    diameter,img = self.getDiameter(self.getEdgeFrame(i))
  File "D:\uDROP_Generation.py", line 444, in getDiameter
    im2, contours, hierarchy = cv2.findContours(arr, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
ValueError: not enough values to unpack (expected 3, got 2)

**Comment by chrizrodz** [comment]
Sorry about that, the opencv library updated and broke some of the code. Try pulling my last commit and running this again. Let me know if that fixes it.

**Comment by shenyigang** [comment]
I downloaded the last commit, it works so well.  Thanks for your kind help.

**Comment by rkrishnasanka** [comment]
@chrizrodz you need to fix the version number of OpenCV required as a dependency. I use `pipenv` (https://pipenv.readthedocs.io/en/latest/) for this.
